---

driver:
  name: digitalocean
  size: s-2vcpu-4gb
  private_networking: false
  region: lon1
  tags: do_test_pool
  firewalls: <%= ENV['DO_FIREWALL_ID'] %>

transport:
  ssh_key: ~/.ssh/id_rsa.do-buildbot

# verifier:
#   format: junit
#   output: reports/inspec/junit/<%= Time.now.strftime("%Y_%m_%d") %>/%{platform}_%{suite}_<%= Time.now.strftime("%H_%M_%S") %>_inspec.xml
#   name: inspec
#   # sudo: true
#   format: junit
#   output: reports/inspec/junit/%{platform}_%{suite}_<%= Time.now %>_inspec.xml

platforms:
  - name: debian-9
#   - name: debian-8
  - name: ubuntu-18
  - name: ubuntu-17
  - name: ubuntu-16
  - name: centos-7
  # - name: centos-6
  - name: fedora-27
  #- name: ubuntu-17-10-x64
  #- name: ubuntu-17-10-x64
  - name: fedora-28
  # - name: oracle-7.4
  # - name: oracle-6.9

suites:
  - name: default
    extra_vars:
      elk_features:
        - elasticsearch