---

- tags: [ elk ]
  block:

    # boilerplate
  - name: bootstrap enough that ansible can run most modules
    include_tasks: "bootstrap/main.yml"
    when: bootstrap_done is not defined
    tags: [ bootstrap ]

    # boilerplate
  - include_tasks: bootstrap/distro-vars-import.yml
    tags: always

    ## START OF MAIN TASKS SECTION ##


  - include_tasks: install/main.yml
    tags: always

  - name: configure features
    include_tasks: "opt/{{ elk_feature }}.yml"
    with_items: "{{ elk_features }}"
    loop_control:
      loop_var: elk_feature
    tags: always

    ## END OF MAIN TASKS SECTION ##

  # boilerplate
  # the idea here, is that if any of the tasks fail, it will add useful
  # troubleshooing tools to the build, for inspection.
  rescue:
  - debug:
      msg: "As the run has failed, I am going to install debugging utils"

  - include_tasks: bootstrap/distro-debug-packages.yml

  - fail:
      msg: "force a failure due to previous errors"
