---

  # sudo apt-get update && sudo apt-get install elasticsearch

  - name: install the latest version of elasticsearch
    package:
      name:
        - elasticsearch
      state: present

  - name: configure elasticsearch settings
    template:
      src: elasticsearch/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: root
      mode: 0644
    notify:
    - restart elasticsearch
    tags:
      - config
  #  when: server_name is defined

  - service:
      name: elasticsearch
      state: started
      enabled: yes

  - elasticsearch_plugin:
      name: ingest-user-agent
      state: present

  - elasticsearch_plugin2:
      name: ingest-geoip
      state: present


  - name: install the modules
    shell: |
      plugins="$(/usr/share/elasticsearch/bin/elasticsearch-plugin list)"

      echo $plugins
      installed=""

      [[ $plugins =~ "ingest-user-agent" ]] || \
      {
        /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-user-agent -b
        installed=1
      }

      [[ $plugins =~ "ingest-geoip" ]] || \
      {
      /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip -b
      installed=1
      }

      [[ $installed ]] && service elasticsearch force-reload || true

    args:
      executable: /bin/bash
    # notify:
    # - restart elasticsearch
